### ISSUE TITLE
Error in CSV export

### ISSUE THREAD

**Issue by Kalimaha** [FENIX-Platform/fenix-ui-olap#27]
Commas misplaced in the CSV output. For instance, in the following example output:

```
"Element","Element Code","Country","Country Code","Item","Item Code","2012",unit,flag
"Production", "5510", "Afghanistan", "2", "Apples", "515", "70"",tonnes"","
```
Commas are misplaced in the last two columns: ``` "70"",tonnes""," ```

**Comment by deneb1** [comment]
export is an external function of the olap, the implementation at the project side is only a call to an external webservice by now
